services:
  - type: web
    name: worktrack
    env: node
    buildCommand: npm install
    startCommand: npx tsx server/index.ts
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: SESSION_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false