
services:
  - type: web
    name: timetrack
    env: node
buildCommand: npm install && cd client && npm install && npm run build && cd .. && npm run build    
startCommand: NODE_ENV=production node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /api/health
